// Code generated by tygo. DO NOT EDIT.

//////////
// source: addon.go

export interface ManifestResource {
  name: string;
  types: string[];
  idPrefixes: string[];
}
export interface Manifest {
  id: string;
  name: string;
  description: string;
  version: string;
  resources: ManifestResource[];
  types: string[];
}
export interface Stream {
  name: string;
  title: string;
  url: string;
  infoHash: string;
  addonName: string;
}
export interface Addon {
  URL: string;
  Manifest: Manifest;
}
