// Code generated by tygo. DO NOT EDIT.

//////////
// source: library.go

export type Status = string;
export const StatusWatchLater: Status = "watch_later";
export const StatusWatching: Status = "watching";
export const StatusFinished: Status = "finished";
export const StatusDropped: Status = "dropped";
/**
 * LibraryEntry mirrors the `library_entries` Supabase table.
 */
export interface LibraryEntry {
  id: string; // UUIDv4
  user_id?: string; // null until Supabase auth is wired up
  tmdb_id: number /* int */;
  media_type: string; // "movie" | "tv"
  title: string;
  poster_path: string;
  status: Status;
  rating?: number /* float64 */; // 0.0–5.0; null = unrated
  vote_average: number /* float64 */; // TMDB community rating, stored for offline display
  /**
   * TV tracking — used for "new episodes" detection and resume labels
   */
  last_air_date: string; // TMDB last_air_date; empty for movies
  last_watched_at?: string; // updated every time progress is saved
  last_watched_season?: number /* int */; // most recently watched TV episode
  last_watched_episode?: number /* int */; // most recently watched TV episode
  last_aired_season?: number /* int */; // TMDB last_episode_to_air.season_number
  last_aired_episode?: number /* int */; // TMDB last_episode_to_air.episode_number
  added_at: string;
  updated_at: string;
}
/**
 * WatchProgress mirrors the `watch_progress` Supabase table.
 * One row per unique (tmdb_id, media_type, season, episode) tuple.
 */
export interface WatchProgress {
  id: string;
  user_id?: string;
  library_entry_id: string;
  tmdb_id: number /* int */;
  media_type: string;
  season?: number /* int */; // null for movies
  episode?: number /* int */; // null for movies
  position_seconds: number /* float64 */;
  duration_seconds: number /* float64 */;
  completed: boolean;
  watched_at: string;
}
