// Code generated by tygo. DO NOT EDIT.

//////////
// source: hls.go


//////////
// source: player.go

/**
 * AudioTrackInfo describes a single audio track returned by ffprobe.
 */
export interface AudioTrackInfo {
  index: number /* int */;
  language: string;
  title: string;
  codec: string;
}
/**
 * SubtitleTrackInfo describes a single subtitle track returned by ffprobe.
 */
export interface SubtitleTrackInfo {
  index: number /* int */;
  language: string;
  title: string;
  codec: string;
}
