// Code generated by tygo. DO NOT EDIT.

//////////
// source: settings.go

/**
 * Settings holds all user-configurable preferences persisted to disk.
 * Add new fields here; they'll be zero-valued on first load and safe to extend.
 */
export interface Settings {
  /**
   * Playback
   */
  openOnMute: boolean; // start videos muted
  defaultVolume: number /* float64 */; // 0.0–1.0
  autoPlay: boolean; // autoplay next episode
  rememberPosition: boolean; // resume from last position
  /**
   * Provider / streams
   */
  defaultProvider: string; // e.g. "torrentio", "debrid"
  preferHLS: boolean; // use HLS pipeline over direct stream
  /**
   * Subtitles
   */
  subtitlesEnabled: boolean;
  defaultSubtitleLang: string; // ISO 639-1 e.g. "en"
  defaultAudioLang: string; // ISO 639-1 e.g. "en"
  /**
   * UI
   */
  showStreamDetails: boolean; // show codec/resolution badges on stream list
}
