// Code generated by tygo. DO NOT EDIT.

//////////
// source: tmdb.go

/**
 * Client talks to the TMDB API. It owns the API key (previously threaded
 * through every function as a parameter) and the HTTP client (previously a
 * package global). Holding both on a struct lets callers construct independent
 * clients and inject a custom HTTP client in tests. Fields are unexported, so
 * tygo emits nothing for Client — only the data types (Media, Details,
 * MediaImages, ...) cross into the generated TS.
 */
export interface Client {
}
export interface Media {
  id: number /* int */;
  title: string;
  name: string;
  overview: string;
  release_date: string;
  first_air_date: string;
  poster_path: string;
  vote_average: number /* float64 */;
  media_type: string;
  trailer_url: string;
  clip_urls: string;
  images: string[];
  popularity: number /* float64 */;
  genre_ids?: number /* int */[];
  adult?: boolean;
}
export interface MediaDetails {
  imdb_id: string;
}
export interface TVExternalIds {
  imdb_id: string;
}
/**
 * TVSeason is a season summary returned by /tv/{id}.
 */
export interface TVSeason {
  season_number: number /* int */;
  episode_count: number /* int */;
  name: string;
  poster_path: string;
}
/**
 * TVEpisode is a single episode returned by /tv/{id}/season/{n}.
 */
export interface TVEpisode {
  episode_number: number /* int */;
  name: string;
  overview: string;
  still_path: string;
  air_date: string;
}
export interface Details {
  /**
   * Overview was missing entirely — TMDB always returns it, but Go's JSON
   * decoder silently drops any source field with no matching destination
   * field, so it never survived the unmarshal in GetDetails below.
   */
  overview: string;
  genres: {
    id: number /* int */;
    name: string;
  }[];
  runtime: number /* int */;
  episode_run_time: number /* int */[];
  credits: {
    cast: {
      name: string;
    }[];
  };
  release_dates: {
    results: {
      iso_3166_1: string;
      release_dates: {
        certification: string;
      }[];
    }[];
  };
  content_ratings: {
    results: {
      iso_3166_1: string;
      rating: string;
    }[];
  };
  keywords: {
    keywords: {
      id: number /* int */;
      name: string;
    }[]; // movies
    results: {
      id: number /* int */;
      name: string;
    }[]; // tv shows
  };
  origin_country: string[];
  number_of_seasons: number /* int */;
  number_of_episodes: number /* int */;
  seasons: TVSeason[];
  /**
   * LastEpisodeToAir is TV-only. Used client-side to detect unwatched new
   * episodes by comparing season/episode_number against the user's
   * last-watched position.
   */
  last_episode_to_air?: {
    season_number: number /* int */;
    episode_number: number /* int */;
    air_date: string;
  };
  /**
   * NextEpisodeToAir is TV-only and only present while the show is still
   * airing. Used to power the "Upcoming" widget — null once a show has
   * ended or gone on indefinite hiatus with nothing scheduled.
   */
  next_episode_to_air?: {
    name: string;
    season_number: number /* int */;
    episode_number: number /* int */;
    air_date: string;
    still_path: string;
  };
}
export interface Keyword {
  id: number /* int */;
  name: string;
}
export interface MediaImageObject {
  aspect_ratio: number /* float32 */;
  height: number /* int */;
  iso_639_1: string;
  file_path: string;
  url: string;
  vote_average: number /* float32 */;
  vote_count: number /* int */;
  width: number /* int */;
}
export interface MediaImages {
  backdrops: MediaImageObject[];
  logos: MediaImageObject[];
  posters: MediaImageObject[];
}
export interface MediaVideoObject {
  iso_639_1: string;
  name: string;
  key: string;
  site: string;
  size: number /* int */;
  type: string;
  official: boolean;
  published_at: string;
  embed_url: string;
}
export interface MediaVideos {
  results: MediaVideoObject[];
}
/**
 * DiscoverParams configures one /discover query. with_genres / with_keywords
 * are OR'd (pipe) to broaden recall; without_genres is comma-joined to exclude
 * all listed.
 */
export interface DiscoverParams {
  MediaType: string; // "movie" | "tv" (required)
  Page: number /* int */; // 1-based; 0 lets TMDB default to 1
  SortBy: string; // default "popularity.desc"
  WithGenres: number /* int */[];
  WithoutGenres: number /* int */[];
  WithKeywords: number /* int */[];
  MinVoteCount: number /* float64 */;
  MinVoteAverage: number /* float64 */;
  IncludeAdult: boolean;
  Region: string;
  CertCountry: string; // movie-only; e.g. "US"
  CertLTE: string; // movie-only; e.g. "PG"
}
export interface DiscoverResult {
  results: Media[];
  page: number /* int */;
  total_pages: number /* int */;
}
