// Code generated by tygo. DO NOT EDIT.

//////////
// source: tmdb.go

export interface Media {
  id: number /* int */;
  title: string;
  name: string;
  overview: string;
  release_date: string;
  first_air_date: string;
  poster_path: string;
  vote_average: number /* float64 */;
  media_type: string;
  trailer_url: string;
  images: string[];
  popularity: number /* float64 */;
}
export interface MediaDetails {
  imdb_id: string;
}
export interface TVExternalIds {
  imdb_id: string;
}
/**
 * TVSeason is a season summary returned by /tv/{id}.
 */
export interface TVSeason {
  season_number: number /* int */;
  episode_count: number /* int */;
  name: string;
  poster_path: string;
}
/**
 * TVEpisode is a single episode returned by /tv/{id}/season/{n}.
 */
export interface TVEpisode {
  episode_number: number /* int */;
  name: string;
  overview: string;
  still_path: string;
  air_date: string;
}
export interface Details {
  genres: {
    name: string;
  }[];
  runtime: number /* int */;
  episode_run_time: number /* int */[];
  credits: {
    cast: {
      name: string;
    }[];
  };
  release_dates: {
    results: {
      iso_3166_1: string;
      release_dates: {
        certification: string;
      }[];
    }[];
  };
  content_ratings: {
    results: {
      iso_3166_1: string;
      rating: string;
    }[];
  };
  keywords: {
    keywords: {
      name: string;
    }[]; // movies
    results: {
      name: string;
    }[]; // tv shows
  };
  origin_country: string[];
  number_of_seasons: number /* int */;
  number_of_episodes: number /* int */;
  seasons: TVSeason[];
}
export interface Keyword {
  id: number /* int */;
  name: string;
}
