// Code generated by tygo. DO NOT EDIT.

//////////
// source: tmdb.go

export interface Media {
  id: number /* int */;
  title: string;
  name: string;
  overview: string;
  release_date: string;
  first_air_date: string;
  poster_path: string;
  vote_average: number /* float64 */;
  media_type: string;
  trailer_url: string;
  images: string[];
}
export interface MediaDetails {
  imdb_id: string;
}
export interface Details {
  genres: {
    name: string;
  }[];
  runtime: number /* int */;
  episode_run_time: number /* int */[];
  credits: {
    cast: {
      name: string;
    }[];
  };
  release_dates: {
    results: {
      iso_3166_1: string;
      release_dates: {
        certification: string;
      }[];
    }[];
  };
  content_ratings: {
    results: {
      iso_3166_1: string;
      rating: string;
    }[];
  };
  keywords: {
    keywords: {
      name: string;
    }[]; // movies
    results: {
      name: string;
    }[]; // tv shows
  };
}
