// Code generated by tygo. DO NOT EDIT.
/* eslint-disable @typescript-eslint/no-explicit-any */
//////////
// source: activity.go
/*
Package activity maintains a per-profile watch-time log, crediting playback
seconds from /api/library/progress ticks into date/hour buckets without any
player changes. The on-disk store is a single JSON file
(activity-{profileID}.json) following the same debounced-persist pattern as
internal/library: markDirty coalesces rapid ticks into a single write ~1s
out; Flush() forces an immediate write on shutdown.
*/

/**
 * DayEntry holds per-day watch-time broken down by hour and by title.
 */
export interface DayEntry {
  /**
   * ByHour accumulates seconds of playback credit for each clock-hour (0–23)
   * of the day in local time. Lets the activity page render an
   * "hours by time-of-day" histogram without scanning every day entry.
   */
  by_hour: number /* int64 */[];
  /**
   * ByTitle maps "tmdbID:mediaType" → cumulative seconds for this day.
   * Key format matches the entryKey() idiom in internal/library: "12345:movie"
   * for movies, "12345:tv" for shows (title-level, not episode-level).
   */
  by_title: { [key: string]: number /* int64 */};
}
/**
 * LibraryLookup is the slice of *library.Library the activity handler needs
 * to enrich TitlesWatchedThisYear with display metadata. *library.Library
 * satisfies it. Keeping it as an interface lets tests inject a stub without
 * a real on-disk library.
 */
export type LibraryLookup = any;
/**
 * Store is the per-profile activity log. All exported methods are safe for
 * concurrent use.
 */
export interface Store {
}
/**
 * TitleSeconds holds per-title watch-time for the current year, enriched with
 * display metadata when a LibraryLookup is wired in.
 */
export interface TitleSeconds {
  tmdb_id: number /* int */;
  media_type: string;
  seconds: number /* int64 */;
  title?: string;
  poster_path?: string;
}
/**
 * Stats is the response shape for GET /api/library/activity.
 */
export interface Stats {
  total_seconds: number /* int64 */;
  total_titles: number /* int */;
  current_streak: number /* int */;
  longest_streak: number /* int */;
  avg_seconds_per_active_day: number /* int64 */;
  titles_this_year: number /* int */;
  this_year_seconds: number /* int64 */;
  last_year_seconds: number /* int64 */;
  by_year: { [key: string]: number /* int64 */};
  by_month_this_year: number /* int64 */[]; // 0 = Jan
  by_month_last_year: number /* int64 */[];
  by_day_of_week: number /* int64 */[]; // 0 = Sun
  by_hour_of_day: number /* int64 */[];
  calendar: { [key: string]: number /* int64 */}; // non-zero days only
  titles_watched_this_year: TitleSeconds[]; // top ~20 by seconds
}
