// Code generated by tygo. DO NOT EDIT.

//////////
// source: addon.go
/*
Package addons manages Stremio-compatible provider/subtitle addons and a
couple of bespoke "official" integrations (JustWatch availability, IntroDB
timestamps) that aren't Stremio addons at all despite sharing the same
AddonEntry shape. Fan-out across multiple enabled addons of the same kind
runs one goroutine per addon under an overall deadline, with per-addon
failures swallowed — one broken or slow addon should never break or stall
the ones that work.
*/

export type AddonKind = string;
export type AddonSource = string;
export const KindProvider: AddonKind = "provider";
export const KindSubtitle: AddonKind = "subtitle";
export const KindTimestamps: AddonKind = "timestamps";
export const SourceOfficial: AddonSource = "official";
export const SourceStremio: AddonSource = "stremio";
export interface ManifestResource {
  name: string;
  types: string[];
  idPrefixes: string[];
}
/**
 * ManifestCatalogExtra describes one parameterisation dimension for a catalog
 * (e.g. genre, skip). IsRequired true means the catalog can't be browsed
 * without supplying that parameter — i.e. it's search-only.
 */
export interface ManifestCatalogExtra {
  name: string;
  isRequired: boolean;
}
/**
 * ManifestCatalog is one catalog declared in a Stremio addon manifest. The
 * custom UnmarshalJSON normalises both the modern extra:[{name,isRequired}]
 * form and the legacy extraRequired/extraSupported:[]string form into the
 * unified Extra field.
 */
export interface ManifestCatalog {
  type: string;
  id: string;
  name: string;
  extra?: ManifestCatalogExtra[];
}
export interface Manifest {
  id: string;
  name: string;
  description: string;
  version: string;
  resources: ManifestResource[];
  types: string[];
  catalogs?: ManifestCatalog[];
}
export interface AddonEntry {
  id: string;
  url?: string;
  manifest: Manifest;
  kind: AddonKind;
  source: AddonSource;
  enabled: boolean;
  /**
   * DisabledCatalogs tracks per-catalog opt-outs. An absent key means the
   * catalog is enabled (default-on, only explicit opt-outs are stored,
   * mirroring how OfficialEnabled works for official addons). Persists via
   * the existing addonStore JSON encode in store.go.
   */
  disabledCatalogs?: { [key: string]: boolean};
}
/**
 * StremioMeta is one item from a Stremio catalog response.
 */
export interface StremioMeta {
  id: string;
  type: string;
  name: string;
  poster: string;
  description: string;
  releaseInfo: string;
}
/**
 * CatalogRef is the DTO for a single enabled catalog sent to the frontend.
 */
export interface CatalogRef {
  addonId: string;
  addonName: string;
  catalogType: string;
  catalogId: string;
  name: string;
}
export interface Subtitle {
  id: string;
  url: string;
  lang: string;
}
/**
 * StreamBehaviorHints is the subset of Stremio's behaviorHints object we
 * retain. VideoSize, when present, is a structured byte size — more reliable
 * than parsing the free-text title — and is promoted into Stream.SizeBytes
 * by classifyStream when SizeBytes is unset.
 */
export interface StreamBehaviorHints {
  notWebReady?: boolean;
  bingeGroup?: string;
  videoSize?: number /* int64 */;
}
export interface Stream {
  name: string;
  title: string;
  url: string;
  infoHash: string;
  addonName: string;
  subtitles?: Subtitle[];
  /**
   * SizeBytes is the stream's file size when the source reports it as a
   * structured number (currently only Nuvio scrapers). Zero means unknown —
   * callers fall back to parsing a size out of Title text (the ubiquitous
   * but unstructured "💾 1.4 GB" convention used by most Stremio addons).
   */
  sizeBytes?: number /* int64 */;
  /**
   * Headers are extra HTTP headers (e.g. Referer/Origin) the origin CDN
   * requires. Only Nuvio-sourced streams set this today; when present,
   * /api/play proxies the request instead of redirecting, since a bare
   * redirect can't carry them to the origin.
   */
  headers?: { [key: string]: string};
  /**
   * BehaviorHints is the raw hints object from the addon response. They were
   * previously dropped at decode because the field didn't exist; adding it
   * lets encoding/json pick them up. classifyStream promotes VideoSize into
   * SizeBytes when the latter is unset.
   */
  behaviorHints?: StreamBehaviorHints;
  /**
   * Cached is true when confirmed debrid-cached (instant retrieval).
   * Classifier is conservative, prefers false-negatives.
   */
  cached?: boolean;
  /**
   * Debrid is the detected debrid service ("RealDebrid", "AllDebrid",
   * "Premiumize", "TorBox", "Offcloud", "Debrid-Link", or generic "Debrid");
   * set for cached and uncached debrid streams; empty for plain
   * torrents/unknown direct streams.
   */
  debrid?: string;
}
/**
 * WatchOption represents a streaming service availability entry from JustWatch.
 */
export interface WatchOption {
  providerId: number /* int */;
  providerName: string;
  logoPath: string;
  type: string; // "flatrate", "rent", or "buy"
  link: string; // JustWatch/provider page to open in browser
}

//////////
// source: debrid.go


//////////
// source: introdb.go

/**
 * TimestampSegment is a single timed segment (intro, recap, credits, or preview).
 * StartMs or EndMs may be nil: nil start means beginning of file, nil end means end of file.
 */
export interface TimestampSegment {
  start_ms?: number /* int64 */;
  end_ms?: number /* int64 */;
}
/**
 * TimestampData holds all segment timestamps for a media item or episode.
 */
export interface TimestampData {
  intro?: TimestampSegment[];
  recap?: TimestampSegment[];
  credits?: TimestampSegment[];
  preview?: TimestampSegment[];
}

//////////
// source: manager.go

/**
 * Manager owns the configured addon registry and the HTTP client used to talk
 * to addons. Fields are unexported, so tygo emits nothing for Manager — only
 * the data types (AddonEntry, Stream, Subtitle, WatchOption, etc.) cross into
 * the generated TS.
 */
export interface Manager {
}

//////////
// source: store.go

