// Code generated by tygo. DO NOT EDIT.

//////////
// source: addon.go

export type AddonKind = string;
export type AddonSource = string;
export const KindProvider: AddonKind = "provider";
export const KindSubtitle: AddonKind = "subtitle";
export const SourceOfficial: AddonSource = "official";
export const SourceStremio: AddonSource = "stremio";
export interface ManifestResource {
  name: string;
  types: string[];
  idPrefixes: string[];
}
export interface Manifest {
  id: string;
  name: string;
  description: string;
  version: string;
  resources: ManifestResource[];
  types: string[];
}
export interface AddonEntry {
  id: string;
  url?: string;
  manifest: Manifest;
  kind: AddonKind;
  source: AddonSource;
  enabled: boolean;
}
export interface Subtitle {
  id: string;
  url: string;
  lang: string;
}
export interface Stream {
  name: string;
  title: string;
  url: string;
  infoHash: string;
  addonName: string;
  subtitles?: Subtitle[];
}
/**
 * WatchOption represents a streaming service availability entry from JustWatch.
 */
export interface WatchOption {
  providerId: number /* int */;
  providerName: string;
  logoPath: string;
  type: string; // "flatrate", "rent", or "buy"
  link: string; // JustWatch/provider page to open in browser
}

//////////
// source: manager.go

/**
 * Manager owns the configured addon registry and the HTTP client used to talk
 * to addons. Fields are unexported, so tygo emits nothing for Manager — only
 * the data types (AddonEntry, Stream, Subtitle, WatchOption, etc.) cross into
 * the generated TS.
 */
export interface Manager {
}

//////////
// source: store.go

