// Code generated by tygo. DO NOT EDIT.

//////////
// source: addon.go

export interface ManifestResource {
  name: string;
  types: string[];
  idPrefixes: string[];
}
export interface Manifest {
  id: string;
  name: string;
  description: string;
  version: string;
  resources: ManifestResource[];
  types: string[];
}
export interface Subtitle {
  id: string;
  url: string;
  lang: string;
}
export interface Stream {
  name: string;
  title: string;
  url: string;
  infoHash: string;
  addonName: string;
  subtitles?: Subtitle[];
}
export interface Addon {
  URL: string;
  Manifest: Manifest;
}
/**
 * Fall back to object form
 */
export type Alias = ManifestResource;

//////////
// source: manager.go

/**
 * Manager owns the configured addon registry and the HTTP client used to talk
 * to addons. This state used to live in package globals; holding it on a struct
 * lets callers construct independent managers (and tests inject a custom client
 * or pre-seed the registry). Fields are unexported, so tygo emits nothing for
 * Manager — only the data types (Manifest, Stream, Subtitle, Addon) cross into
 * the generated TS.
 * in memory for now, will move to SQLite later
 */
export interface Manager {
}
