// Code generated by tygo. DO NOT EDIT.

//////////
// source: calendar.go
/*
Package calendar owns the GET /api/library/calendar endpoint, which returns
a merged timeline of:
  - "available" items: episodes or movies the user has in their library that
    have aired/released but not yet been watched.
  - "episode" items: upcoming episodes airing within the next 90 days for
    shows the user is watching or has in watch-later.
  - "movie" items: upcoming theatrical/digital releases within the next 90
    days for movies in the user's library.
*/

/**
 * CalendarItem is one scheduled event in the user's release calendar.
 */
export interface CalendarItem {
  date: string; // YYYY-MM-DD; for kind="available" it's the item's air/release date
  kind: string; // "episode" | "movie" | "available"
  tmdb_id: number /* int */;
  media_type: string; // "tv" | "movie"
  title: string;
  poster_path: string;
  season_number?: number /* int */; // nil for movies
  episode_number?: number /* int */; // nil for movies
  episode_name: string;
  still_path: string;
  waiting_count: number /* int */; // aired-but-unwatched count for kind="available" TV
}
/**
 * Server owns the /api/library/calendar handler.
 */
export interface Server {
}
