// Code generated by tygo. DO NOT EDIT.

//////////
// source: library.go

export type Status = string;
export const StatusWatchLater: Status = "watch_later";
export const StatusWatching: Status = "watching";
export const StatusFinished: Status = "finished";
export const StatusDropped: Status = "dropped";
/**
 * LibraryEntry mirrors the `library_entries` Supabase table.
 */
export interface LibraryEntry {
  id: string; // UUIDv4
  user_id?: string; // null until Supabase auth is wired up
  tmdb_id: number /* int */;
  media_type: string; // "movie" | "tv"
  title: string;
  poster_path: string;
  status: Status;
  rating?: number /* float64 */; // 0.0–5.0; null = unrated
  vote_average: number /* float64 */; // TMDB community rating, stored for offline display
  /**
   * TV tracking — used for "new episodes" detection and resume labels
   */
  last_air_date: string; // TMDB last_air_date; empty for movies
  last_watched_at?: string; // updated every time progress is saved
  last_watched_season?: number /* int */; // most recently watched TV episode
  last_watched_episode?: number /* int */; // most recently watched TV episode
  last_aired_season?: number /* int */; // TMDB last_episode_to_air.season_number
  last_aired_episode?: number /* int */; // TMDB last_episode_to_air.episode_number
  added_at: string;
  updated_at: string;
}
/**
 * WatchProgress mirrors the `watch_progress` Supabase table.
 * One row per unique (tmdb_id, media_type, season, episode) tuple.
 */
export interface WatchProgress {
  id: string;
  user_id?: string;
  library_entry_id: string;
  tmdb_id: number /* int */;
  media_type: string;
  season?: number /* int */; // null for movies
  episode?: number /* int */; // null for movies
  position_seconds: number /* float64 */;
  duration_seconds: number /* float64 */;
  completed: boolean;
  watched_at: string;
}
/**
 * Dismissal records a "not interested" — a title to keep out of recommendations
 * and to nudge taste away from, without it being a library shelf entry.
 */
export interface Dismissal {
  tmdb_id: number /* int */;
  media_type: string;
  dismissed_at: string;
}
/**
 * TasteSignal is the minimal per-title signal the discover package needs,
 * without exposing the library's internals.
 */
export interface TasteSignal {
  TmdbID: number /* int */;
  MediaType: string;
  Status: Status;
  UserRating?: number /* float64 */; // user's 0–5 rating; nil if unrated
  Completed: boolean; // any progress record for this title is completed
  Dismissed: boolean;
}
export interface Stats {
  total: number /* int */; // library entries (dismissals excluded)
  by_type: { [key: string]: number /* int */}; // entries per media type
  by_status: { [key: string]: number /* int */}; // status -> count
  finished: { [key: string]: number /* int */}; // finished entries per type
  dismissed: number /* int */;
  rated: number /* int */;
  avg_rating: number /* float64 */; // mean user rating over rated titles, 0–5
  movie_share: number /* float64 */; // preference, from finished+watching counts
  tv_share: number /* float64 */;
}
/**
 * Library ── Service ──────────────────────────────────────────────────────────────────
 * Library owns all of the package's mutable state. It used to live in package
 * globals; holding it on a struct lets callers construct (and tests spin up)
 * independent instances, and removes the hidden coupling between Init and the
 * handlers. Fields are unexported on purpose: nothing outside this package
 * touches them, and keeping them unexported means tygo emits nothing for this
 * type — only the JSON data types (LibraryEntry, WatchProgress, diskStore)
 * cross into the generated TS.
 */
export interface Library {
}
