// Code generated by tygo. DO NOT EDIT.

//////////
// source: manager.go

/**
 * Manager owns the configured Nuvio repo registry. Fields are unexported, so
 * tygo emits nothing for Manager — only the data types (Repo, Scraper, etc.)
 * cross into the generated TS.
 */
export interface Manager {
}

//////////
// source: nuvio.go
/*
Package nuvio adds support for Nuvio-style native JS scraper plugins — a
different ecosystem than the Stremio-compatible addons in internal/addons.
A "repo" is a GitHub repository publishing a manifest.json that lists
scraper entries; each scraper is a JS file executed in an embedded goja VM
(see runtime.go) to produce direct stream URLs.

This is deliberately kept separate from addons.Manager: internal/tmdb's
batch quality-probe endpoint fans addons.Manager.GetAllStreams out across
every title in a discovery grid, and must not incur goja startup + arbitrary
third-party network calls per grid tile. Only internal/player's single-title
/api/streams handler calls into this package.
*/

/**
 * ScraperManifestEntry is one scraper's entry in a repo's manifest.json.
 */
export interface ScraperManifestEntry {
  id: string;
  name: string;
  description?: string;
  version?: string;
  filename: string;
  supportedTypes?: string[];
  logo?: string;
  contentLanguage?: string[];
  supportsExternalPlayer?: boolean;
}
/**
 * Scraper is a manifest entry plus Cove-local state. Enabled is Cove's own
 * per-scraper opt-in toggle — deliberately independent of whatever "enabled"
 * value ships in the upstream manifest, since that reflects the repo author's
 * default, not the user's consent to run third-party JS.
 * ScraperManifestEntry's fields are duplicated here (not embedded) on
 * purpose: Go's encoding/json flattens anonymous embedded structs onto the
 * parent object, but tygo does not — an embedded field would generate a TS
 * type with a nested `scraperManifestEntry` property that doesn't match the
 * actual flat JSON the backend sends.
 */
export interface Scraper {
  id: string;
  name: string;
  description?: string;
  version?: string;
  filename: string;
  supportedTypes?: string[];
  logo?: string;
  contentLanguage?: string[];
  supportsExternalPlayer?: boolean;
  enabled: boolean;
  code?: string; // cached JS source; empty until first enable
  codeFetchedAt?: string;
  codeErr?: string; // last fetch/parse error, surfaced in UI
}
/**
 * Repo is a user-added GitHub repository publishing Nuvio-style scrapers.
 */
export interface Repo {
  id: string; // "owner/repo"
  owner: string;
  repo: string;
  branch: string;
  url: string; // original user-pasted URL, for display
  enabled: boolean;
  scrapers: Scraper[];
  fetchedAt: string;
  fetchErr?: string;
}

//////////
// source: runtime.go


//////////
// source: store.go

