// Code generated by tygo. DO NOT EDIT.

//////////
// source: player.go

/**
 * Player owns all of the package's mutable state — the torrent client and the
 * active-torrent registry — plus the injected TMDB client and addon manager.
 * Fields are unexported, so tygo emits nothing for Player.
 */
export interface Player {
}
