// Code generated by tygo. DO NOT EDIT.

//////////
// source: hls.go


//////////
// source: player.go

/**
 * Player owns all of the package's mutable state — the torrent client, the
 * active-torrent registry, the HLS session table, and the subtitle cache (all
 * previously package globals) — plus the injected TMDB client and addon
 * manager that used to be threaded through SetupHandlers. Its methods are split
 * across player.go and hls.go but all hang off this one type. Fields are
 * unexported, so tygo emits nothing for Player.
 */
export interface Player {
}
/**
 * AudioTrackInfo describes a single audio track returned by ffprobe.
 */
export interface AudioTrackInfo {
  index: number /* int */;
  language: string;
  title: string;
  codec: string;
}
/**
 * SubtitleTrackInfo describes a single subtitle track returned by ffprobe.
 */
export interface SubtitleTrackInfo {
  index: number /* int */;
  language: string;
  title: string;
  codec: string;
}
