// Code generated by tygo. DO NOT EDIT.

//////////
// source: profiles.go
/*
Package profiles manages local, Netflix-style user profiles — not to be
confused with content-rating/kid-mode, which is a separate, unrelated
concept inside internal/discover. Switching the active profile reloads
library, settings, and addons in place via an onChange callback the caller
registers in New(), so those packages never need their own profile-
switching logic.
*/

/**
 * Profile is one named identity within a Cove installation. A single Supabase
 * account can own many profiles; each profile has its own library, settings,
 * and addon config stored in separate files on disk.
 */
export interface Profile {
  id: string;
  name: string;
  is_primary: boolean;
  supabase_uid?: string; // nil = guest / local-only
  name_updated_at: string; // last time Name was changed; zero = unknown
}
/**
 * Store owns the profile list and the currently active profile ID.
 */
export interface Store {
}
