// Code generated by tygo. DO NOT EDIT.

//////////
// source: settings.go
/*
Package settings persists a single flat Settings struct per profile as
JSON, served whole-object over GET/PUT with no partial-merge semantics —
a PUT that omits a field writes its Go zero value, not the previous
value. Select-style preferences (e.g. streamSelectionMode,
discoveryAlgorithm) are plain strings with no server-side enum
validation; the frontend owns the allowed-value metadata and UI.
*/

/**
 * Settings holds all user-configurable preferences persisted to disk.
 */
export interface Settings {
  /**
   * Playback
   */
  openOnMute: boolean; // start videos muted
  defaultVolume: number /* float64 */; // 0.0–1.0
  autoPlay: boolean; // autoplay next episode
  rememberPosition: boolean; // resume from last position
  /**
   * Provider / streams
   */
  defaultProvider: string;
  /**
   * Stream auto-selection
   */
  autoSelectStream: boolean; // skip the manual stream list and play immediately
  streamSelectionMode: string; // "balanced" | "seeders" | "quality" | "smallest" | "bandwidth"
  measuredBandwidthMbps: number /* float64 */; // from the in-app speed test; 0 = never measured
  sourcePreference: string; // "" (none) | "torrent" | "direct" — additive ranking boost, doesn't exclude
  /**
   * Subtitles
   */
  subtitlesEnabled: boolean;
  defaultSubtitleLang: string; // ISO 639-1 e.g. "en"
  defaultAudioLang: string; // ISO 639-1 e.g. "en", or "original" to match the title's original_language
  subtitleSize: number /* float64 */; // percentage, 50–200
  subtitlePosition: number /* float64 */; // percent from bottom, 2–90
  subtitleBackground: boolean; // dark box behind subtitle text
  /**
   * UI
   */
  uiLanguage: string; // "" until first frontend boot, then "en" | "tr"
  showStreamDetails: boolean; // show codec/resolution badges on stream list
  hideSpoilers: boolean;
  /**
   * Segment skip (via IntroDB)
   */
  autoSkipIntro: boolean;
  autoSkipRecap: boolean;
  autoSkipCredits: boolean;
  autoSkipPreview: boolean;
  /**
   * Onboarding
   */
  onboardingDone: boolean;
  /**
   * Discovery
   */
  discoveryAlgorithm: string; // "smart" | "popularity" | "custom"
  customAlgorithmUrl: string; // used when discoveryAlgorithm == "custom"
  /**
   * Predictive prefetch (Phase E) — background-warms stream caches for
   * continue-watching titles and next episodes so playback starts near-
   * instantly. Default true; the worker checks this each cycle and the
   * completion-trigger respects it too.
   */
  prefetchStreams: boolean;
  /**
   * PrefetchNextEpisode background-downloads the next TV episode's top-ranked
   * torrent stream once the current episode's file finishes downloading, so
   * playback of the next episode starts near-instantly. Default true.
   */
  prefetchNextEpisode: boolean;
  /**
   * AllowUploading enables uploading pieces to peers while streaming (capped
   * at 1 MiB/s in the player). Improves download speed via BitTorrent
   * reciprocity — tit-for-tat peers unchoke us faster when we reciprocate.
   * Off means never upload. Default true.
   */
  allowUploading: boolean;
  /**
   * ProbeStreams enables the pre-playback liveness probe: before auto-select
   * commits to a stream, the top direct-URL candidates are HEAD-checked so
   * dead scraper links get demoted instead of failing at playback. Costs
   * ~700ms of auto-select latency; some CDNs refuse HEAD, in which case the
   * probe falls back to a 1-byte Range GET.
   */
  probeStreams: boolean;
  /**
   * Remote access (Phase 5) — opens a separate LAN listener so other devices
   * (e.g. the Android app in thin-client mode) can reach this backend over the
   * local network. Settings are per-profile; remote access follows whichever
   * profile is currently active.
   * RemoteAccessEnabled: when true the server opens a separate TCP listener on
   * 0.0.0.0:<main-port+1> (default 0.0.0.0:6970). The main loopback listener
   * (127.0.0.1:6969) is never touched. When false, the LAN port is simply
   * closed — a port scan gets connection-refused, not a 403.
   * RemoteAccessToken: a 32-byte hex string generated once (crypto/rand) the
   * first time RemoteAccessEnabled is set to true, then persisted and never
   * auto-rotated. Every request arriving on the LAN listener must supply this
   * token via X-Cove-Token header or ?token= query param.
   * NOTE: these two fields are intentionally excluded from Supabase sync
   * (see MergeFrom). They are device-local security config and must not
   * propagate to other devices.
   */
  remoteAccessEnabled: boolean;
  remoteAccessToken: string;
  /**
   * AllowLanStreamSources permits /api/play to proxy stream URLs that resolve
   * to LAN or loopback addresses. Off by default (SSRF hardening); enable only
   * when streaming from a local media server on the same network (e.g. Jellyfin,
   * Plex). Per-device config — not synced via Supabase.
   */
  allowLanStreamSources: boolean;
  /**
   * Trakt.tv integration — both fields are roaming (synced via Supabase
   * MergeFrom like all other preference fields; no exclusion needed).
   * TraktScrobbleEnabled sends start/pause/stop events to Trakt as the user
   * watches. Default true so scrobbling is active immediately after linking;
   * the handler is a no-op when the account isn't connected.
   */
  traktScrobbleEnabled: boolean;
  /**
   * TraktSyncEnabled enables the background two-way history and watchlist
   * sync (Phase 2). Default false — opt-in because it modifies the library.
   */
  traktSyncEnabled: boolean;
  /**
   * Sync bookkeeping — stamped server-side on every local write, used to resolve
   * Supabase merge conflicts (see MergeFrom). Never trust a client-supplied value.
   */
  updatedAt: string;
}
/**
 * Store owns the package's mutable state. Fields are unexported, so tygo emits
 * nothing for Store — only the Settings data type crosses into the generated TS.
 */
export interface Store {
}
