// Code generated by tygo. DO NOT EDIT.

//////////
// source: settings.go

/**
 * Settings holds all user-configurable preferences persisted to disk.
 * Add new fields here; they'll be zero-valued on first load and safe to extend.
 */
export interface Settings {
  /**
   * Playback
   */
  openOnMute: boolean; // start videos muted
  defaultVolume: number /* float64 */; // 0.0–1.0
  autoPlay: boolean; // autoplay next episode
  rememberPosition: boolean; // resume from last position
  /**
   * Provider / streams
   */
  defaultProvider: string; // e.g. "torrentio", "debrid"
  preferHLS: boolean; // use HLS pipeline over direct stream
  /**
   * Stream auto-selection
   */
  autoSelectStream: boolean; // skip the manual stream list and play immediately
  streamSelectionMode: string; // "balanced" | "seeders" | "quality" | "smallest" | "bandwidth"
  measuredBandwidthMbps: number /* float64 */; // from the in-app speed test; 0 = never measured
  /**
   * Subtitles
   */
  subtitlesEnabled: boolean;
  defaultSubtitleLang: string; // ISO 639-1 e.g. "en"
  defaultAudioLang: string; // ISO 639-1 e.g. "en"
  subtitleSize: number /* float64 */; // percentage, 50–200
  subtitlePosition: number /* float64 */; // percent from bottom, 2–90
  subtitleBackground: boolean; // dark box behind subtitle text
  /**
   * UI
   */
  showStreamDetails: boolean; // show codec/resolution badges on stream list
  hideSpoilers: boolean;
  /**
   * Segment skip (via IntroDB)
   */
  autoSkipIntro: boolean;
  autoSkipRecap: boolean;
  autoSkipCredits: boolean;
  autoSkipPreview: boolean;
}
/**
 * Store ── Service ──────────────────────────────────────────────────────────────────
 * Store owns the package's mutable state (previously package globals). The
 * data type is already named Settings, so the service is named Store; New
 * returns *Store and the handlers hang off it. Fields are unexported, so tygo
 * emits nothing for Store — only the Settings data type crosses into the
 * generated TS.
 */
export interface Store {
}
