// Code generated by tygo. DO NOT EDIT.

//////////
// source: tmdb.go
/*
Package tmdb wraps The Movie Database API and registers the largest single
group of HTTP routes in the app (search, details, images, videos,
providers, similar-titles, genre lists, a batched quality-probe endpoint).
TMDB concerns only live here — anything resembling personalization or
taste scoring belongs in internal/discover instead, which depends on this
package for raw metadata but never the reverse.
*/

/**
 * Client talks to the TMDB API. Fields are unexported, so tygo emits nothing
 * for Client — only the data types (Media, Details, MediaImages, ...) cross
 * into the generated TS.
 */
export interface Client {
}
export interface Media {
  id: number /* int */;
  title: string;
  name: string;
  overview: string;
  release_date: string;
  first_air_date: string;
  poster_path: string;
  vote_average: number /* float64 */;
  media_type: string;
  trailer_url: string;
  clip_urls: string;
  images: string[];
  popularity: number /* float64 */;
  genre_ids?: number /* int */[];
  adult?: boolean;
  /**
   * OriginalLanguage is the ISO 639-1 code TMDB stores the title's original
   * audio/language as (e.g. "ja" for a Japanese show). TMDB populates this on
   * both list endpoints (search/discover) and single-item lookups
   * (GetMediaByID), so no extra request is needed to get it.
   */
  original_language?: string;
}
export interface MediaDetails {
  imdb_id: string;
}
export interface TVExternalIds {
  imdb_id: string;
}
/**
 * TVSeason is a season summary returned by /tv/{id}.
 */
export interface TVSeason {
  season_number: number /* int */;
  episode_count: number /* int */;
  name: string;
  poster_path: string;
}
/**
 * TVEpisode is a single episode returned by /tv/{id}/season/{n}.
 */
export interface TVEpisode {
  episode_number: number /* int */;
  name: string;
  overview: string;
  still_path: string;
  air_date: string;
  /**
   * Runtime in minutes, as reported by TMDB's season endpoint; 0 when TMDB
   * doesn't know it. Lets "mark as watched" record the episode's real
   * duration instead of a placeholder.
   */
  runtime: number /* int */;
}
export interface Details {
  overview: string;
  genres: {
    id: number /* int */;
    name: string;
  }[];
  runtime: number /* int */;
  episode_run_time: number /* int */[];
  /**
   * ReleaseDate is the theatrical/digital release date in YYYY-MM-DD form.
   * Movies only; empty for TV.
   */
  release_date: string;
  credits: {
    cast: {
      id: number /* int */;
      name: string;
      order: number /* int */;
    }[];
    crew: {
      id: number /* int */;
      name: string;
      job: string;
    }[];
  };
  release_dates: {
    results: {
      iso_3166_1: string;
      release_dates: {
        certification: string;
      }[];
    }[];
  };
  content_ratings: {
    results: {
      iso_3166_1: string;
      rating: string;
    }[];
  };
  keywords: {
    keywords: {
      id: number /* int */;
      name: string;
    }[]; // movies
    results: {
      id: number /* int */;
      name: string;
    }[]; // tv shows
  };
  origin_country: string[];
  /**
   * ProductionCompanies is the list of studios that produced this title
   * (movies and TV). Present in the base details response — no extra
   * append_to_response needed.
   */
  production_companies: {
    id: number /* int */;
    name: string;
  }[];
  /**
   * Networks is the list of TV networks this show aired on (TV only).
   */
  networks: {
    id: number /* int */;
    name: string;
  }[];
  /**
   * Status is TMDB's lifecycle label for a TV show (for example
   * "Returning Series", "Ended", or "Canceled"). Empty for movies.
   */
  status: string;
  number_of_seasons: number /* int */;
  number_of_episodes: number /* int */;
  seasons: TVSeason[];
  /**
   * LastEpisodeToAir is TV-only. Used client-side to detect unwatched new
   * episodes by comparing season/episode_number against the user's
   * last-watched position.
   */
  last_episode_to_air?: {
    season_number: number /* int */;
    episode_number: number /* int */;
    air_date: string;
  };
  /**
   * NextEpisodeToAir is TV-only and only present while the show is still
   * airing. Used to power the "Upcoming" widget — null once a show has
   * ended or gone on indefinite hiatus with nothing scheduled.
   */
  next_episode_to_air?: {
    name: string;
    season_number: number /* int */;
    episode_number: number /* int */;
    air_date: string;
    still_path: string;
  };
}
/**
 * Person is a /search/person result. KnownFor carries a few representative
 * titles TMDB attaches to the person, so a search for "Jackie Chan" can surface
 * his films alongside the person entry itself.
 */
export interface Person {
  id: number /* int */;
  name: string;
  profile_path: string;
  known_for_department: string;
  popularity: number /* float64 */;
  known_for: Media[];
}
/**
 * Provider is a streaming/rental service from /watch/providers. TMDB has no
 * name-search for providers, so SearchProviders fetches the regional directory
 * and filters by name.
 */
export interface Provider {
  provider_id: number /* int */;
  provider_name: string;
  logo_path: string;
  display_priority: number /* int */;
}
/**
 * SearchResults is the sectioned payload for /api/search/multi.
 */
export interface SearchResults {
  movies: Media[];
  tv: Media[];
  people: Person[];
  providers: Provider[];
}
/**
 * PersonDetails is the full /person/{id} payload used by the person overlay:
 * biography plus a deduped, popularity-sorted filmography (combined_credits).
 */
export interface PersonDetails {
  id: number /* int */;
  name: string;
  biography: string;
  profile_path: string;
  known_for_department: string;
  birthday: string;
  place_of_birth: string;
  credits: Media[];
}
export interface Keyword {
  id: number /* int */;
  name: string;
}
export interface MediaImageObject {
  aspect_ratio: number /* float32 */;
  height: number /* int */;
  iso_639_1: string;
  file_path: string;
  url: string;
  vote_average: number /* float32 */;
  vote_count: number /* int */;
  width: number /* int */;
}
export interface MediaImages {
  backdrops: MediaImageObject[];
  logos: MediaImageObject[];
  posters: MediaImageObject[];
}
export interface MediaVideoObject {
  iso_639_1: string;
  name: string;
  key: string;
  site: string;
  size: number /* int */;
  type: string;
  official: boolean;
  published_at: string;
  embed_url: string;
}
export interface MediaVideos {
  results: MediaVideoObject[];
}
/**
 * DiscoverParams configures one /discover query. with_genres / with_keywords
 * are OR'd (pipe) to broaden recall; without_genres is comma-joined to exclude
 * all listed.
 */
export interface DiscoverParams {
  MediaType: string; // "movie" | "tv" (required)
  Page: number /* int */; // 1-based; 0 lets TMDB default to 1
  SortBy: string; // default "popularity.desc"
  WithGenres: number /* int */[];
  WithoutGenres: number /* int */[];
  WithKeywords: number /* int */[];
  WithoutKeywords: number /* int */[];
  WithPeople: number /* int */[]; // matches either cast or crew credits
  MinVoteCount: number /* float64 */;
  MinVoteAverage: number /* float64 */;
  IncludeAdult: boolean;
  Region: string;
  CertCountry: string; // movie-only; e.g. "US"
  CertLTE: string; // movie-only; e.g. "PG"
}
export interface DiscoverResult {
  results: Media[];
  page: number /* int */;
  total_pages: number /* int */;
}
