// Code generated by tygo. DO NOT EDIT.

//////////
// source: updater.go
/*
Package updater implements self-update via GitHub releases. The check is
skipped entirely on Linux (the only distribution channels there are
Flatpak and the AUR PKGBUILD package, both of which own their own updates
— Flatpak via flatpak/Flathub, PKGBUILD via pacman; self-extracting a
release tarball over either would corrupt the package manager's view of
installed files) and on dev builds (non-semver version string). Applying
an update exits the process with code 42, a sentinel the Qt shell watches
for to know it should restart the backend rather than treating the exit
as a crash.
*/

/**
 * RestartExitCode is the exit code the Go backend uses to signal the Qt shell
 * to restart (picking up new binaries and web assets). The shell connects to
 * the backend's finished signal and calls QProcess::startDetached on this code.
 */
export const RestartExitCode = 42;
/**
 * CheckResult is the JSON payload returned by GET /api/update/check.
 */
export interface CheckResult {
  available: boolean;
  current_version: string;
  latest_version: string;
  release_name: string;
}
